### ISSUE TITLE
COVID-2.1 Test Credentials

### ISSUE THREAD

**Issue by msalitu** [alastria/alastria-identity-JSON-objects#8]
https://github.com/alastria/alastria-identity/wiki/Alastria-DID-Method-Specification-(Quorum-version)#21-alastria-did-scheme

**Comment by nmanero** [comment]
I've just sent the pull request. 
I think everything is tested except the claim, inside the credentialSubject.
The levelOfAssurance is tested but not the other property as sometimes it can be just a key:value with the value being a string or an object.

**Comment by nmanero** [comment]
Although this task is already closed, I've noticed one thing while testing that every hex. starts with 0x
In the exampleCredentials, we use tokensFactory.tokens.createCredential to create a credential and we pass the context as a parameter. 
In those examples, context is taken from configuration.json, from "context" and its value is an URL.
We need to decide whether in credentials, @context must be only a URL, an array of 2 (url and "JWT" or anything, in order to fix the test or fix the examples

In comment above, Maria, you say that it must be an array but in examples is only a URL.
Let's talk about it and I adapt the tests

**Comment by VictorNS69** [comment]
As long as I know, the context in a credential is an array 
![image](https://user-images.githubusercontent.com/10101065/82118194-d3498500-9775-11ea-94d1-8427917fa7fe.png)
Also in a presentation 
![image](https://user-images.githubusercontent.com/10101065/82118210-e9efdc00-9775-11ea-9d92-8dadf67e0d8e.png)
And this is the definition of context
![image](https://user-images.githubusercontent.com/10101065/82118247-30ddd180-9776-11ea-8d52-b6b898582017.png)

All images taken from: https://github.com/alastria/alastria-identity/wiki/Alastria-DID-Method-Specification-(Quorum-version)#42-presentation-payload
